tutorials/01_simplicial_complexes.ipynb

The  notebook's .html page looks great, with all images showing.
Only the thumbnail does not show.
It also does not show on the .ipynb.
Thus we try using an image that shows on the .ipynb as thumbnail.

Try another img that shows on the ipynb file

---

pyproject.toml

HyperNetX 2.0.0.post1 introduced breaking changes compared to 1.2.5. See also #38.

Restrict dependency HyperNetX to < 2.0.0

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/test.yml

This PR bumps the python version from 3.9 to 3.10.11 so that the github action workflows in toponetx use the same python version as the one used in the workflows from topomodelx.

Bump to Python 3.10.11 in GitHub Actions

---

pyproject.toml
test/datasets/test_utils.py
toponetx/classes/simplicial_complex.py
toponetx/datasets/utils.py

This PR adds a `datasets` folder where standard datasets on topological domains can be added. the `utils.py` module allows users to load each dataset through a single point of entry, like a `load_*()` function.
To exemplify this, this PR adds the PPI (protein-protein-interaction) dataset.
While the PPI dataset is loaded in networkx graph format, the functionalities in `transform/` can be used to lift that graph into another topological domain.

Add protein-protein-interaction dataset loading in nx.Graph format

---

test/classes/test_cell_complex.py
toponetx/classes/cell_complex.py

From #40:
>`CellComplex.incidence_matrix()` for nodes returns a $1\times n$ matrix instead of $0\times n$ (seems incorrect, but maybe something depends on this behavior?)
> - with `index=True`, it returns an empty row index list, but matrix has one row.
> - with `index=True` it also returns the indices in the wrong (inconsistent with higher ranks) order

Fix CellComplex incidence matrix and test case

---

toponetx/classes/complex.py

The usage of `abc.abstractstaticmethod` was wrong in the abstract complex class, as the methods are not static (and `abc.abstractstaticmethod` is deprecated anyway).
That being said, currently these decorators have no effect at the moment, as the `Complex` class does not derive from `abc.ABC`, see #59.

Fix wrong usage of `abc.abstractstaticmethod`

---

toponetx/classes/cell_complex.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/simplicial_complex.py

Even though the constructor of the superclass is currently empty, it is generally a good idea to always call it anyway. This avoids issues down the line if eventually something is added to the superclass.

Add missing calls to constructors of superclass

---

toponetx/classes/cell.py
toponetx/classes/cell_complex.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/hyperedge.py
toponetx/classes/node.py
toponetx/classes/reportview.py
toponetx/classes/simplex.py

The `collections.abc` module is available since Python 3.3. As the minimum required Python version for TopoNetX is 3.9, the fallback is unnecessary.

Cleanup imports from `collections.abc`

---

test/utils/test_structure.py
toponetx/utils/structure.py

- typing > neighborhood_list_to_neighborhood_dict was called with iterable (in a different function), but list was specified -- since only an iterable was needed, I relaxed the type hint.
- same function used dictionary tried to use an undefined variable

Fix errors discovered by mypy

---

toponetx/algorithms/spectrum.py
toponetx/classes/cell.py
toponetx/classes/cell_complex.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/complex.py
toponetx/classes/node.py
toponetx/classes/reportview.py
toponetx/classes/simplex.py
toponetx/classes/simplicial_complex.py
toponetx/datasets/utils.py
toponetx/transform/graph_to_simplicial_complex.py
toponetx/utils/structure.py

These changes format the docstrings to follow NumPy's style guide in more places. In particular:
- There is only one section `Examples` containing all examples. It is also called `Examples` even if there is only one example (currently).
- Use built-in Python types (e.g., bool instead of boolean).

Cleanup docstrings

---

test/classes/test_cell_complex.py
toponetx/classes/cell_complex.py

Since the functionality was partially duplicated and having seperate methods for nodes, edges, and cells seemed to serve no purpose beyond confusing our users, I unified all functionality into get_cell_attributes and set_cell_attributes.
Of course, this breaks multiple things. If you prefer, I can make everything compatible with the old way it works, but this will only clutter up our code and set unexpected default values. If there are no or few users who's code we break, I would prefer the cleaner way.
- `set_cell_attributes` now requires rank (could set default to 2)
- `set_node_attributes`, `set_edge_attributes` and respective getters don't exist anymore (could re-add them to simply call the new methods)
I also replaced some code with calls to respective NetworkX functions as it did …

[BREAKING CHANGES] Clean up attribute getter / setter for CellComplex

---

toponetx/classes/cell_complex.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/simplicial_complex.py

This cleans up some of the examples given in docstrings. In particular, some of the examples weren't executable at all, because non-existent functions were called.
Ref. #95

Cleanup examples in docstrings

---

.pre-commit-config.yaml
pyproject.toml

The pre-commit hooks didn't work for me.
- old isort version could apparently not be installed (see also https://stackoverflow.com/questions/75269700/pre-commit-fails-to-install-isort-5-11-4-with-error-runtimeerror-the-poetry-co)
- from .gitignore, using .venv for the virtual environment seems correct, but isort and flake8 considered source files of dependencies

Fix pre-commit hook config

---

toponetx/classes/simplicial_complex.py

Removes the now-obsolete documentation for the `mode` parameter of `SimplicialComplex`, see #106.

Remove init mode documentation from SimplicialComplex

---

toponetx/classes/cell_complex.py
toponetx/classes/reportviews.py
toponetx/utils/structure.py

The pull request #116 introduced type annotations that are not compatible with Python 3.9 (our minimum supported version), in particular union type expressions are only available since Python 3.10. Replace them with `typing.Union`.
In addition, this pull request uses subscripting on the build-in `dict`, `list`, `set` and `tuple` classes, which is available since Python 3.9. The respective classes inside the `typing` module are no longer necessary and have been deprecated.

Fix typing annotations for Python 3.9

---

toponetx/classes/cell_complex.py

itertools.pairwise was introduced in Python 3.10, but we support 3.9 as well.
See also #128

Replace itertools.pairwise with nx.utils.pairwise

---

.github/workflows/test.yml

With this change, our tests are run once for each supported Python version. For the future, this should prevent errors as fixed by #123 before they are merged.

Run test suite on latest release of all supported python versions

---

test/classes/test_complex.py
test/classes/test_simplicial_complex.py
toponetx/classes/cell_complex.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/simplicial_complex.py

All complexes have a `dim()` method as per the `Complex` contract. However, simplicial and cell complexes had an identical second method under another name for the same purpose.
This pull request deprecates these methods and unifies everything to the method dictated by the `Complex` contract for consistency. I kept the old methods with a warning for now since they may be used by some downstream consumers already -- lets remove them with a future release.

Cleanup functions regarding dimension of complexes

---

toponetx/classes/cell_complex.py
toponetx/classes/simplicial_complex.py
toponetx/datasets/mesh.py

Using Python's [`pathlib`](https://docs.python.org/3/library/pathlib.html) module is a bit cleaner than low-level `os.path` calls.

Use python's `pathlib` module instead of low-level `os.path` calls

---

test/classes/test_complex.py
toponetx/classes/complex.py

This method is not used anywhere, and it is not clear why a complex inherently needs a cache anyway.

Remove `Complex._clear_cache`

---

test/classes/test_simplicial_complex.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/complex.py
toponetx/classes/reportviews.py
toponetx/classes/simplicial_complex.py

The `shape` property now always is a tuple and may be empty for empty complexes.

Unify `shape` properties of complexes

---

toponetx/classes/cell.py
toponetx/classes/cell_complex.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/complex.py
toponetx/classes/hyperedge.py
toponetx/classes/reportviews.py
toponetx/classes/simplex.py
toponetx/classes/simplicial_complex.py

`str`s are considered immutable and thus are safe to use as default parameter values.

Simplify `name` parameters

---

.github/workflows/test.yml
pyproject.toml
toponetx/classes/cell_complex.py
toponetx/classes/reportviews.py
toponetx/datasets/graph.py
toponetx/datasets/mesh.py
toponetx/utils/structure.py

As outlined in #161, the minimum Python version is inconsistent across our packages, which will be fixed by this pull request and others for the other repositories.
For `TopoNetX`, this moves the package from Python 3.9+ to Python 3.10+, allowing us to use some new typing features. In particular, `typing.Optional` and `typing.Union` are deprecated and replaced by [union type expressions](https://docs.python.org/3/library/stdtypes.html#types-union).

Unify python version across packages

---

test/classes/test_simplicial_complex.py
toponetx/classes/simplicial_complex.py

This method doesn't work. Setting simplex attributes doesn't go through `SimplicialComplex.__setitem__` but through `SimplicialComplex.__getitem__` and `SimplexView.__getitem__`.

Remove `SimplicialComplex.__setitem__` method

---

toponetx/classes/cell_complex.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/complex.py
toponetx/classes/simplicial_complex.py

The `name` is common to all complexes, so let's add it to the `Complex` superclass.
For the future, the dedicated `name` parameter should be removed. Users can store an identifiable name just as well inside complex attributes.

Extract name attribute into `Complex` superclass

---

test/transform/test_graph_to_simplicial_complex.py
toponetx/__init__.py
toponetx/datasets/graph.py
toponetx/transform/graph_to_simplicial_complex.py

Old method names are still available but raise a deprecation warning.

Rename transform methods from graphs to simplicial complexes

---

test/classes/test_simplicial_complex.py
toponetx/classes/simplicial_complex.py

@mhajij 
Adding few test cases to SimplicialComplex
- test_from_spharpy
- test_normalized_laplacian_matrix
- test_add_node (Edge cases)
- test_add_simplex (Edge cases)
Minor fix - Removing unreachable else condition for add_simplex:
add_simplex accepts - Hashable, or Iterable, or str, or Simplex objects (which cover all base objects, thus dangling else logic is unreachable)

adding tests and a minor fix for SimplicialComplex

---

test/classes/test_complex.py
test/classes/test_hyperedge.py
test/classes/test_reportviews.py
toponetx/classes/hyperedge.py
toponetx/classes/reportviews.py

Removing the previous test case as it seemed to be passing despite removing Complex ABC from class inheritance of ConcreteComplex.

Adding test cases for Cell Complex Abstract Class. 

---

toponetx/classes/combinatorial_complex.py

When adding cells/hyperedges to a Combinatorial Complexes with some attributes, especially nodes, it doesn't work as the dictionnaries are updated not in the right order. Here is a short snippet of code to replicate the unexpected result:
`from toponetx.classes.combinatorial_complex import CombinatorialComplex
CC = CombinatorialComplex()
atom_id = 0
atom_symbol = 'C'
CC.add_cell(
(atom_id,),
rank=0,
symbol=atom_symbol
)
print(CC.cells.hyperedge_dict[0])
The few changes in combinatorial_complexes.py that I propose fix this issue.

Fix attributes when adding cells in CombinatorialComplex

---

test/classes/test_cell_complex.py
toponetx/classes/cell_complex.py

the following methods were added
1- get_linegraph : the simplest graph that can be attached to a cell complex
2- all_cell_to_node_codjacnecy_matrix 
3-node_to_all_cell_adjacnecy_matrix
based on the above the following methods were corrected
1- s_connected_components
2- s_component_subcomplexes
3- connected_components
4- connected_component_subcomplexes
5- node_diameters
6- cell_diameters
7- diameter
8- cell_diameter
9- distance
10- cell_distance

Fix cell complex methods

---

test/algorithms/test_spectrum.py
test/classes/test_simplicial_complex.py
toponetx/datasets/graph.py
toponetx/datasets/mesh.py

I guess this is a bit of a controversial one, but I would suggest to remove the default value for the `complex_type` parameters in the datasets. It is not obvious why a simplicial complex is returned by default but you can switch to a cell complex.
This way, the user has to be explicit about what they want and their code is more readable. Plus this makes type hints easier on our end (overloads with default values aren't nice...) 😄

Remove default complex type value in datasets

---

toponetx/transform/graph_to_simplicial_complex.py

[`nx.enumerate_all_cliques`](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.clique.enumerate_all_cliques.html) guarantees that cliques are yielded in ascending order. We can thus abort calling the generator once the the first clique of larger dimension than requested is returned.
This improves performance, as cliques of size larger than `max_dim` are not computed anymore. Previously, *all* cliques have been computed, only to immediately discard those that are too large.

Improve performance of graph to clique complex lifting

---

test/transform/test_graph_to_simplicial_complex.py
toponetx/transform/graph_to_simplicial_complex.py

With this pull request, any node, edge, and graph attributes will be copied over to the clique complex. In a sense, the simplicial complex is exactly as the input graph, only that all cliques are filled-in with higher-order simplices.

Copy attributes in clique lifting

---

test/classes/test_combinatorial_complex.py
toponetx/classes/colored_hypergraph.py
toponetx/classes/combinatorial_complex.py

@mhajij please merge this onto the open PR for fix hypergraph #225

FIX: typehints and docstring changes for ColoredHyperGraph

---

test/classes/test_complex.py
toponetx/classes/complex.py

The methods inside `Complex` are abstract and don't have an implementation. The test case was basically only there to make test coverage happy, because the `pass` statement is considered code that is not covered otherwise. We can remove the superfluous `pass` statements instead.

Clean up `Complex` ABC

---

toponetx/algorithms/spectrum.py
toponetx/classes/cell_complex.py
toponetx/classes/colored_hypergraph.py
toponetx/classes/complex.py
toponetx/classes/simplicial_complex.py

Even though weights are largely not implemented yet, many functions already have a `weight` parameter. This pull request fixes this weight parameter throughout the code base to be consistent and to make mypy happy (ref. #163).

Fix `weight` parameter throughout source code

---

test/classes/test_simplex.py
toponetx/classes/simplex.py

This pull request deprecates `Simplex.boundary` and `Simplex.faces`. As a simplex has no knowledge of the SC it belongs to, the sub-simplices returned by both functions lack any user-defined parameters that were given when constructing the simplicial complex. Going through appropriate methods in `SimplicialComplex` avoids this problem.
With the deprecation of the above functions, I also removed the simplex tree construction inside of the `Simplex` class. The default value `construct_tree=True` meant a significant performance implication.
In fact, we have fallen into this trap ourself inside TopoNetX at least once: The `Simplex` construction in `SimplicialComplex.__init__` does not set this parameter to false even though it definitely should have been.

Deprecate simplex tree construction in `Simplex`.

---

toponetx/classes/cell.py
toponetx/classes/colored_hypergraph.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/path.py
toponetx/classes/path_complex.py
toponetx/classes/reportviews.py
toponetx/classes/simplicial_complex.py

`isinstance` takes a tuple as second argument `isinstance(obj, (ONE, TWO))`, which is equivalent to chaining multiple checks `isinstance(obj, ONE) or isinstance(obj, TWO)`. Clean this up across the codebase.

Clean-up `isinstance` calls

---

docs/conf.py

This links occurrences of `networkx.Graph`, `numpy.ndarray` and so on in function signatures to the documentation of the respective project.
| Before | After |
|-------|----|
| <img width="740" alt="Bildschirmfoto 2023-10-27 um 15 42 03" src="https://github.com/pyt-team/TopoNetX/assets/2105496/026472dc-bcf1-4e60-aba8-72336b44d5b5"> | <img width="740" alt="Bildschirmfoto 2023-10-27 um 15 41 28" src="https://github.com/pyt-team/TopoNetX/assets/2105496/ea427291-01e1-4a0c-8d8a-68ec67e25c06"> |
| | (`Graph`, `int` and `None` are linked)

Setup intersphinx for our documentation

---

.github/workflows/test.yml
pyproject.toml

This is a draft pull request to track the progress of adding typing annotations to our codebase. For now it is expected that mypy raises errors.

Add static typechecking with mypy

---

test/utils/test_normalization.py
toponetx/__init__.py
toponetx/classes/complex.py
toponetx/utils/__init__.py
toponetx/utils/normalization.py

often in DL computations normalization must be added to matrices for computations. This file is a collection of popular methods typically used in a DL setting.

normalization added

---

.pre-commit-config.yaml
test/classes/test_cell_complex.py
test/classes/test_simplicial_complex.py
toponetx/classes/cell_complex.py
toponetx/classes/simplicial_complex.py

adding Hasse graph to CC and SC.

adding hasse graph

---

.github/workflows/test.yml
pyproject.toml
test/classes/test_cell_complex.py
test/classes/test_path_complex.py
test/classes/test_simplicial_complex.py
toponetx/classes/cell_complex.py
toponetx/classes/simplicial_complex.py

The requirement on HyperNetX is not hard and is problematic, as it is not compatible with NetworkX 3, which is more than a year old. With this pull request, users that do not use hypergraphs are free to use NetworkX 3, while others must stay on NetworkX 2 (as transient dependency due to HyperNetX).
We exclusively use HyperNetX in places where we transform user-provided hypergraph instances into complex classes or vice versa. Such code points are only ever called when the user itself interacts with HyperNetX and thus did install it themself. We don't need to force that dependency.

Remove hard requirement for `hypernetx`.

---

test/classes/test_cell_complex.py
test/classes/test_colored_hypergraph.py
test/classes/test_combinatorial_complex.py
test/classes/test_hyperedge.py
test/classes/test_path.py
test/classes/test_path_complex.py
test/classes/test_reportviews.py
test/classes/test_simplex.py
test/classes/test_simplicial_complex.py
toponetx/classes/cell.py
toponetx/classes/cell_complex.py
toponetx/classes/colored_hypergraph.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/complex.py
toponetx/classes/hyperedge.py
toponetx/classes/path.py
toponetx/classes/path_complex.py
toponetx/classes/reportviews.py
toponetx/classes/simplex.py
toponetx/classes/simplicial_complex.py

In most cases, some user-defined name can be stored in a complex or atom attribute anyway, there is no need for a separate implementation.

Remove `name` feature across codebase

---

docs/api/index.rst
docs/api/readwrite.rst
test/readwrite/test_atomlist.py
toponetx/readwrite/__init__.py
toponetx/readwrite/atomlist.py
toponetx/readwrite/serialization.py

Introduce functions for "atom lists", which work similar to edge lists and allow to store and load complexes.
Background: Right now, we ship some datasets in form of pickled data structures. While this was a fast way to implement this problem, it is a really bad idea for various reasons. It is highly unstable as it relies on internal state of data structures and any change to them breaks the datasets. In fact, this is what blocks #220, which completely overhauls the internals of `SimplicialComplex`.

Add atomlist to store and read complexes

---

pyproject.toml
test/classes/test_cell.py
test/classes/test_cell_complex.py
test/classes/test_combinatorial_complex.py
test/classes/test_reportviews.py
toponetx/algorithms/components.py
toponetx/algorithms/distance.py
toponetx/algorithms/distance_measures.py
toponetx/algorithms/spectrum.py
toponetx/classes/cell.py
toponetx/classes/cell_complex.py
toponetx/classes/colored_hypergraph.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/path_complex.py
toponetx/classes/reportviews.py
toponetx/classes/simplex.py
toponetx/classes/simplicial_complex.py
toponetx/datasets/graph.py
toponetx/generators/random_simplicial_complexes.py
toponetx/readwrite/atomlist.py
toponetx/readwrite/serialization.py
toponetx/transform/graph_to_simplicial_complex.py
toponetx/utils/normalization.py
toponetx/utils/structure.py

This pull request activates some additional linting rules and fixes occurring errors as a result of them.
Some noticeable new rules:
- `zip()`: Use the optional `strict` parameter to error when the provided iterables are not of same length. This should catch some erroneous user inputs.
- Remove unnecessary `elif` and `else` branches if the previous branch is guaranteed to return. This reduces indentation and makes the code cleaner.
- Use list comprehensions instead of for-loops to transform lists. [This is more performant](https://docs.astral.sh/ruff/rules/manual-list-comprehension/).

Activate more ruff rules

---

toponetx/classes/cell_complex.py

Previously, the method down_laplacian_matrix was indicating that the possible values were {0, 1} were the actual possible values are {1, 2}.

 Solving typo on cell complex documentation. #338 

---

test/classes/test_combinatorial_complex.py
toponetx/classes/combinatorial_complex.py

The CCC condition is not being checked correctly when inserting a new cell. Bug fixed with this PR. See #315.
Also added a new test to insure this the membership dictionary is being populated correctly, this is implemented to prevent deleting the parts of the code responsible for taking into account this feature.

fixng a bug in CCC

---

test/algorithms/test_distance.py
toponetx/algorithms/components.py
toponetx/algorithms/distance.py
toponetx/algorithms/distance_measures.py
toponetx/classes/colored_hypergraph.py
toponetx/exception.py

Previously, the distance between non-connected elements was set to `np.inf`.  See #343 for reasons why this a bad idea. Following NetworkX, in these cases we now raise a new `TopoNetXNoPathException`.
The previous implementation also silently swallowed too many exceptions and returned infinity, which also swallowed actual implementation errors. They have been fixed with this pull request.
Closes #343.

Raise an exception for distances between non-connected elements.

---

pyproject.toml
toponetx/classes/cell.py
toponetx/classes/cell_complex.py
toponetx/classes/colored_hypergraph.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/complex.py
toponetx/classes/path.py
toponetx/classes/path_complex.py
toponetx/classes/simplex.py
toponetx/classes/simplicial_complex.py

The `Self` return type has been introduced in Python 3.11. It allows to express that the return type is of the current enclosed class while correctly considering subclasses.
As usual, the `Self` type is backported to older versions of Python in `typing-extensions`. We can use the native implementation `typing.Self` once Python 3.11+ is the minimum version.

Use `Self` return type where applicable

---

toponetx/classes/cell_complex.py
toponetx/classes/simplex.py
toponetx/classes/simplicial_complex.py
toponetx/transform/graph_to_simplicial_complex.py

The `@deprecated` decorator has been proposed in PEP 702 and is part of Python 3.13. The huge benefit of the decorator is that it moves deprecations into the type system, allowing type checkers to catch calls to these methods. Runtime `DeprecationWarnings` are raised automatically and only once on first use.
As usual, the `@deprecated` decorator is backported to older versions of Python in `typing_extensions`. We can use the native implementation `warnings.deprecated` once Python 3.13+ is the minimum version.

Use new `@deprecated` decorator

---

test/classes/test_simplicial_complex.py
toponetx/classes/simplicial_complex.py

This pull request makes the implementation of `SimplicialComplex.add_simplex` a bit simpler and allows to introduce changes more easily in the future.
Along the way, an inconsistency when providing a `Simplex` class with attributes and additional `kwargs` in different cases was fixed.

Refactor `SimplicialComplex.add_simplex` function

---

README.md
conftest.py
toponetx/__init__.py
toponetx/algorithms/components.py
toponetx/algorithms/distance.py
toponetx/algorithms/distance_measures.py
toponetx/algorithms/spectrum.py
toponetx/classes/cell.py
toponetx/classes/cell_complex.py
toponetx/classes/colored_hypergraph.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/hyperedge.py
toponetx/classes/path.py
toponetx/classes/path_complex.py
toponetx/classes/reportviews.py
toponetx/classes/simplex.py
toponetx/classes/simplicial_complex.py
toponetx/readwrite/atomlist.py
tutorials/01_simplicial_complexes.ipynb
tutorials/02_cell_complexes.ipynb
tutorials/03_combinatorial_complexes.ipynb
tutorials/04_colored_hypergraphs.ipynb

New import convention for TopoNetX

---

pyproject.toml

As [recommended by Scientific Python](https://learn.scientific-python.org/development/guides/packaging-classic/#PP003), `wheel` should not be part of the build dependencies. It is injected automatically by setuptools when needed.

Remove `wheel` from build dependencies

---

.pre-commit-config.yaml
pyproject.toml
test/classes/test_simplex.py
toponetx/classes/cell_complex.py
toponetx/classes/simplicial_complex.py

https://learn.scientific-python.org/development/guides/pytest/#configuring-pytest

Apply pytest suggestions from scientific python

---

pyproject.toml

- Do not specify Python `target-version` for ruff, it is automatically taken from the project's minimum version.
- `per-file-ignores` moved to the `lint` section.

Clean-up ruff config

---

test/classes/test_simplicial_complex.py

SciPy 1.14 removed to `.A` property on sparse matrices to transform into a dense NumPy array. Use `.toarray()` instead.

Fix tests for scipy 1.14

---

test/classes/test_cell_complex.py
test/classes/test_colored_hypergraph.py
test/classes/test_combinatorial_complex.py
test/classes/test_path_complex.py
test/classes/test_reportviews.py
test/classes/test_simplicial_complex.py
toponetx/classes/cell_complex.py
toponetx/classes/colored_hypergraph.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/complex.py
toponetx/classes/path_complex.py
toponetx/classes/reportviews.py
toponetx/classes/simplicial_complex.py

With this pull request, the dunder methods `__contains__`, `__iter__` and `__getitem__` work consistently across all complex types now:
- `atom in complex` works for any atom now. Previously, depending on the complex class, this was only possible for nodes. Closes #273.
- Iterating over a complex now yields all atoms, not just the nodes. This was previously changed to only iterate over nodes (see #266), but changed now for consistency with other dunder methods. Iterating over the nodes is always possible via the `complex.nodes` property.
- `complex[atom]` is implemented consistently to return the user-defined attributes for that atom. Previously, depending on the complex class, this returned the neighbours of the atom. There are other means to access the neighbours, which may also take …

Consistent dunder methods for all complexes

---

test/classes/test_cell_complex.py
toponetx/algorithms/distance_measures.py
toponetx/classes/cell_complex.py
toponetx/classes/colored_hypergraph.py
toponetx/classes/combinatorial_complex.py
toponetx/utils/structure.py

Fix `incidence_to_adjacency` function

---

.github/workflows/test.yml
pyproject.toml
test/classes/test_simplicial_complex.py

Run our test suite against Python 3.13.
This pull request also mocks the call to gudhi and removes the explicit dependency. Installing Gudhi on Python 3.13 fails on Github Actions. See also #320.
Closes #399.

Test against Python 3.13

---

test/classes/test_cell_complex.py
test/classes/test_complex.py
toponetx/classes/cell_complex.py
toponetx/classes/complex.py
toponetx/classes/path_complex.py
toponetx/classes/reportviews.py

Two atoms are considered equal if they have the same elements. User-defined attributes may differ for equal atoms.

Implement `__eq__` for `Atom`s.

---

toponetx/datasets/mesh.py

With this pull request, we move the `coseg` and `shrec16` datasets from a `pickle` backend to atomlists. We need this change because the `pickle` approach relies on internal data structures to not change, which is a blocker for #220. Plus, it is highly unstable anyway.

Move datasets to atomlists

---

test/classes/test_combinatorial_complex.py
test/classes/test_reportviews.py
test/classes/test_simplex.py
test/classes/test_simplex_trie.py
test/classes/test_simplicial_complex.py
test/transform/test_delaunay.py
toponetx/classes/colored_hypergraph.py
toponetx/classes/combinatorial_complex.py
toponetx/classes/reportviews.py
toponetx/classes/simplex.py
toponetx/classes/simplex_trie.py
toponetx/classes/simplicial_complex.py
toponetx/utils/iterable.py

This implements a simplex trie as presented in [1] as backend data structure for the `SimplicialComplex` class. This is also used in gudhi's SC implementation. However, they do not expose all functionality we need and the data structure is implemented in native code, so we cannot interact with it directly either.
Using a simplex tree should bring some nice performance improvements over the previous approach and fixes some bugs along the way as well. I will add some comparisons later.
[1] Jean-Daniel Boissonnat and Clément Maria. The Simplex Tree: An Efficient Data Structure for General Simplicial Complexes. Algorithmica, pages 1–22, 2014

First Implementation of a Simplex Trie

---

test/classes/test_simplicial_complex.py
toponetx/classes/simplicial_complex.py

This PR fixes a typo in `SimplicialComplex.from_spharapy` (making it consistent with `SimplicialComplex.to_spharapy` and the library name).

Fix from_spharapy naming in SimplicialComplex

---

.github/workflows/deploy.yml
.github/workflows/docs.yml
.github/workflows/test.yml
pyproject.toml

With this commit, dependencies are managed using [`uv`](https://github.com/astral-sh/uv).
Closes #402.

Switch to `uv`
