pyt-team/TopoNetX

- test/classes/test_cell.py
A small fix for the unit test. Mostly to test the new changes are working properly.
> fix unit tests for cell

- toponetx/classes/cell_complex.py
- toponetx/classes/complex.py
I've started improving docstrings in CellComplex (#95) and improved type hints (#102) along the way.
> WIP Improve docstrings / type hints in CellComplex

- README.md
> Fix installation instruction for zsh

- test/classes/test_simplicial_complex.py
[First contribution]
adding few test cases to simplicial complex
1. test case TypeError if Simplices is not Iterable type during init.
2. test case shape property when Simplicial Complex is empty.
3. test case for __str__ method
4. test case for KeyError for non-exisitent simplex in getitem
> adding 4 test cases for simplicial complex

- test/classes/test_simplicial_complex.py
> more test cases for SimplicialComplex

- .github/workflows/docs.yml
> Only deploy docs on push to main

- test/classes/test_complex.py
- toponetx/classes/cell.py
- toponetx/classes/complex.py
- toponetx/classes/hyperedge.py
- toponetx/classes/reportviews.py
- toponetx/classes/simplex.py
- toponetx/classes/simplicial_complex.py
Added type annotations to all of them and ensured that they return integers (some returned `np.ndarray`s)
> Improve `__len__` methods

- test/classes/test_cell_complex.py
This is my first commit, added a test case for cell complex class to test correct assertion is being raised while initializing.
> Added test cases for cell complex, test if asserts are raised in init

- test/classes/test_simplicial_complex.py
- toponetx/classes/cell.py
- toponetx/classes/complex.py
- toponetx/classes/simplex.py
- toponetx/classes/simplicial_complex.py
> Add cloning of simplicial complexes

- test/classes/test_cell_complex.py
- toponetx/classes/cell_complex.py
Adding test cases for Cell Complex. Also removed a redundant return statement from cell complex method.
> Adding Test Cases

- test/classes/test_simplicial_complex.py
few fixes and additional test coverage for SimplicialComplex
> test cases for SimplicialComplex

- test/classes/test_simplicial_complex.py
- toponetx/classes/simplicial_complex.py
There is little reason why we should have e.g. a public `add_simplex` function that only forwards `_add_simplex`.
> Inline internal functions that are only called once

- test/algorithms/test_spectrum.py
- test/classes/test_cell.py
- test/classes/test_cell_complex.py
- test/classes/test_combinatorial_complex.py
- test/classes/test_complex.py
- test/classes/test_hyperedge.py
- test/classes/test_simplex.py
- test/classes/test_simplicial_complex.py
- test/datasets/test_mesh.py
- test/datasets/test_utils.py
- test/transform/test_graph_to_simplicial_complex.py
- test/utils/test_structure.py
- toponetx/classes/cell.py
- toponetx/classes/cell_complex.py
- toponetx/classes/combinatorial_complex.py
- toponetx/classes/simplex.py
- toponetx/classes/simplicial_complex.py
> Remove uses of `unittest` in favour of `pytest`

- test/classes/test_simplex.py
- test/datasets/test_mesh.py
- toponetx/classes/cell_complex.py
- toponetx/classes/combinatorial_complex.py
- toponetx/classes/simplex.py
- toponetx/classes/simplicial_complex.py
- toponetx/datasets/graph.py
when converting a complex to another or restricting it to another. Make sure all features are also transferred properly
> Minor issues : fixing feature transition when converting to other complexes, unit tests for sc, cell complex, hyperedge, fixing ordering issues in sc.

- toponetx/datasets/mesh.py
small fixes to mesh.py docstring
> Mesh docstring fix

- test/classes/test_cell.py
- test/classes/test_simplex.py
- toponetx/classes/cell.py
- toponetx/classes/cell_complex.py
- toponetx/classes/combinatorial_complex.py
- toponetx/classes/complex.py
- toponetx/classes/hyperedge.py
- toponetx/classes/reportviews.py
- toponetx/classes/simplex.py
- toponetx/classes/simplicial_complex.py
See #170. There is probably a lot more that can be unified here, but this should be a good first building block.
> Introduce `Atom` abstract class for elements of a complex

- test/classes/test_combinatorial_complex.py
- toponetx/classes/combinatorial_complex.py
- toponetx/classes/complex.py
- toponetx/classes/reportviews.py
> Add `CombinatorialComplex.clone` and make `Complex` abstract

- toponetx/classes/simplicial_complex.py
Leads to a significant performance improvement.
> Remove unnecessary sorting before frozenset constructions

- test/classes/test_complex.py
- toponetx/algorithms/spectrum.py
- toponetx/classes/cell.py
- toponetx/classes/cell_complex.py
- toponetx/classes/combinatorial_complex.py
- toponetx/classes/complex.py
- toponetx/classes/hyperedge.py
- toponetx/classes/reportviews.py
- toponetx/classes/simplex.py
- toponetx/classes/simplicial_complex.py
- toponetx/read_write.py
- toponetx/utils/structure.py
Most of them have been automatically generated by `autotyping`.
See #102.
> Add more typehints throughout the project

- test/classes/test_cell_complex.py
This commit was also used as a demonstration for Maneel
> Adding test cases for remove nodes method for Cell Complex Class

- test/classes/test_cell_complex.py
- toponetx/classes/cell_complex.py
Adding Test Cases for Cell Complex and minor modification in Cell Complex to replace print statement with exceptions.
> Adding test cases for the Cell Complex Class

- toponetx/classes/cell_complex.py
- toponetx/classes/combinatorial_complex.py
- toponetx/classes/reportviews.py
- toponetx/classes/simplicial_complex.py
Nothing really specific, fixed some documentation issues across the board and added trivial type hints.
> Some cleanup everywhere

- test/classes/test_combinatorial_complex.py
- test/classes/test_simplicial_complex.py
- test/datasets/test_graph.py
- test/datasets/test_mesh.py
- toponetx/classes/combinatorial_complex.py
- toponetx/classes/reportviews.py
- toponetx/datasets/graph.py
- toponetx/datasets/mesh.py
- toponetx/transform/graph_to_cell_complex.py
The current implementation of adding cell in a combinatorial complex is expensive (creates a simplicial complex). Fixing the running time to make it O(n) where n is the size of the added cell
> Fixing adding cell complexity

- test/classes/test_combinatorial_complex.py
- toponetx/classes/combinatorial_complex.py
@mhajij Fixing the failing hardcoded str testcases, and one minor doc string fix.
> Fix failing CCC tests

- test/classes/test_combinatorial_complex.py
- test/classes/test_reportviews.py
- toponetx/classes/colored_hypergraph.py
- toponetx/classes/combinatorial_complex.py
- toponetx/classes/reportviews.py
some consistency issues between CCC and CHG are fixed.
> fixing consistency between CCC and CHG

- test/classes/test_cell_complex.py
- toponetx/classes/cell.py
- toponetx/classes/simplex.py
@mhajij 
Professor, addressing florians comments and the failing test case. No need to keep this as a blocked PR.
Have a few merge conflicts with the latest PR merged by florian so will add my changes after clean up tomorrow.
> fixing failing test and docstrings

- toponetx/algorithms/spectrum.py
- toponetx/classes/cell_complex.py
- toponetx/read_write.py
- toponetx/utils/structure.py
part of series of PRs to address #95 
@ninamiolane @ffl096 
Clean docstrings in toponetx/algorithms:
Clean docstrings in toponetx/utils:
Clean up docstrings in toponetx/classes/cell_complex.py
Clean up docstrings in toponetx/read_write.py
> clean up docstrings and API

- test/classes/test_cell_complex.py
- test/classes/test_simplex.py
- test/utils/test_structure.py
- toponetx/utils/structure.py
part of series of PRs for #246 
adding test cases and a minor fix for toponetx/utils/structure.py
> Increasing test coverage for toponetx

- toponetx/classes/cell_complex.py
- toponetx/classes/simplicial_complex.py
In this PR, changes have been done so that all matrices(incidence,adjacency etc.) are all csr or csc. This tackles issue #166.
> Removing COO matrices

- test/classes/test_colored_hypergraph.py
part of PRs to address #246 
adding test cases for ColoredHyperGraph
@mhajij @ninamiolane with this PR, test coverage is >90%, completing the goal for #246
> Increasing test coverage for TopoNetX (2)

- test/classes/test_cell_complex.py
- test/classes/test_colored_hypergraph.py
- test/classes/test_combinatorial_complex.py
- toponetx/classes/cell_complex.py
- toponetx/classes/colored_hypergraph.py
- toponetx/classes/combinatorial_complex.py
fixing update node attrs  in CHG.
> small fixes chg

- test/algorithms/test_components.py
- test/algorithms/test_distance.py
- test/algorithms/test_distance_measures.py
- test/classes/test_colored_hypergraph.py
Adding test cases for few exceptions in newly added algorithms (distance, cell_distance, distance_measures) as part of #256
> Increasing test coverage for TopoNetX (3)

- pyproject.toml
- test/classes/test_cell_complex.py
- test/classes/test_complex.py
- test/classes/test_path_complex.py
- test/classes/test_reportviews.py
- test/classes/test_simplicial_complex.py
- test/transform/test_graph_to_simplicial_complex.py
- toponetx/classes/combinatorial_complex.py
- toponetx/classes/complex.py
- toponetx/classes/path.py
- toponetx/classes/path_complex.py
- toponetx/classes/reportviews.py
- toponetx/classes/simplicial_complex.py
- toponetx/utils/structure.py
Adds the [`flake8-comprehensions`](https://github.com/adamchainz/flake8-comprehensions) package and cleans up reported problems. See the packages documentation for the list of rules and their reasons.
> Improve comprehensions and enforce codestyle

- test/classes/test_reportviews.py
part of PRs to address #256 
adding test cases for untested methods for View classes
> increasing test coverage for TopoNetX (4)

- test/classes/test_cell_complex.py
- test/classes/test_simplicial_complex.py
- toponetx/classes/cell_complex.py
- toponetx/classes/simplicial_complex.py
Adding dirac operator 
https://arxiv.org/abs/2301.10137
> adding dirac operator

- test/classes/test_colored_hypergraph.py
- test/classes/test_reportviews.py
- toponetx/classes/reportviews.py
- adding testcases for few missed lines in reportviews, fixed two of the bugs in #277 
- adding testcases for CHG matrix methods
> Increasing test coverage for TopoNetX (5)

- test/classes/test_combinatorial_complex.py
- test/classes/test_reportviews.py
- test/classes/test_simplicial_complex.py
- toponetx/classes/combinatorial_complex.py
Minor bug fix for CombinatorialComplex (added raises for few errors, error handling).
Edge case tests for CCC
Edge case tests for HyperEdgeView
Edge case tests for SimplicialComplex
> Increasing test coverage for TopoNetX (6)

- docs/api/algorithms.rst
- docs/api/classes.rst
- docs/api/index.rst
- docs/api/transform.rst
Fixing Issues with generating documenation for the newer modules/methods
> Fixing Issues with generating documenation for the newer modules/methods

- .pre-commit-config.yaml
- pyproject.toml
> Adding pre-commit for checking docstrings

- test/classes/test_combinatorial_complex.py
- toponetx/classes/combinatorial_complex.py
> fixing small bug for singleton

- toponetx/classes/cell_complex.py
- toponetx/classes/complex.py
- toponetx/classes/hyperedge.py
- toponetx/classes/path.py
- toponetx/classes/path_complex.py
- toponetx/classes/reportviews.py
- toponetx/classes/simplex.py
- toponetx/datasets/__init__.py
- toponetx/datasets/graph.py
- toponetx/datasets/mesh.py
- toponetx/generators/__init__.py
- toponetx/generators/classic_cell_complexes.py
- toponetx/transform/__init__.py
- toponetx/transform/graph_to_cell_complex.py
- toponetx/transform/graph_to_simplicial_complex.py
- toponetx/utils/__init__.py
Making some changes to docstrings. 
Note: I am not an expert in this part of the codebase and have changed docstrings based on my understanding.
> Docstring changes to reduce numpydoc validation issues, helps with #178

- test/classes/test_cell_complex.py
- test/classes/test_reportviews.py
- toponetx/classes/reportviews.py
- toponetx/readwrite/atomlist.py
Add a `AtomView` base class to formalise certain similarities and common interfaces between all view classes.
Cf. #170.
> Add `AtomView` abstract class

- test/classes/test_colored_hypergraph.py
- toponetx/classes/colored_hypergraph.py
(1) The code does not handle empty chg.
(2) fixing #288
> small fix to chg addressing empty graph in compute laplacian

- .github/dependabot.yml
For reference, see https://learn.scientific-python.org/development/guides/gha-basic/#GH210
> Maintain GitHub action versions with Dependabot

- README.md
acknowledging funding from NSF
> nsf funding added

- test/classes/test_combinatorial_complex.py
- test/generators/test_classic_cell_complex.py
- test/generators/test_random_cell_complexes.py
- test/generators/test_random_simplicial_complexes.py
- test/readwrite/test_atomlist.py
- test/transform/test_graph_to_cell_complex.py
- toponetx/classes/colored_hypergraph.py
- toponetx/classes/combinatorial_complex.py
- toponetx/classes/simplex.py
- toponetx/datasets/__init__.py
- toponetx/generators/__init__.py
- toponetx/generators/random_simplicial_complexes.py
- toponetx/readwrite/__init__.py
- toponetx/readwrite/serialization.py
- toponetx/utils/__init__.py
- toponetx/utils/normalization.py
- fix dead code in `ColoredHyperGraph._remove_hyperedge`, see #291.
- typos
- whitespace issues
> Minor cleanup

- .github/workflows/deploy.yml
- test/classes/test_colored_hypergraph.py
- test/classes/test_combinatorial_complex.py
- toponetx/classes/colored_hypergraph.py
- toponetx/classes/combinatorial_complex.py
> Remove unreachable code

- toponetx/datasets/.gitignore
- toponetx/datasets/graph.py
- toponetx/datasets/mesh.py
> Move datasets to different url

- test/classes/test_simplicial_complex.py
- toponetx/classes/simplicial_complex.py
> Remove hard dependency on `gudhi`
